# -------------------------
# TypeScript Design Patterns
# -------------------------

.PHONY: install build test clean

install:
	pnpm install

build:
	pnpm build

test:
	pnpm test

coverage:
	pnpm coverage

clean:
	rm -rf node_modules dist
